Repository MYONGSIK/Android, pull requests merged in 2023-03, with the labels that each got.

#40 [Feat/euijin] : 전화번호 및 주소 클릭시 이동 이벤트 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/myongsik/myongsikandroid/data/api/SearchFoodApi.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/SearchFoodPagingSource.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/search/SearchFoodRepositoryImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/di/AppModule.kt
  app/src/main/java/com/myongsik/myongsikandroid/di/RepositoryModule.kt
  app/src/main/java/com/myongsik/myongsikandroid/di/ViewModelFactoryModule.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/SearchFoodViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/HomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/TagFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/SearchViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/SearchViewModelProviderFactory.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/Constant.kt
  app/src/main/res/layout/item_restaurant_food.xml
  app/src/main/res/values/strings.xml
Labels: feat

#43 [Feat/euijin]: 리팩터링 진행
  app/src/main/java/com/myongsik/myongsikandroid/data/model/food/OnSearchViewHolderClick.kt
  app/src/main/java/com/myongsik/myongsikandroid/di/RepositoryModule.kt
  app/src/main/java/com/myongsik/myongsikandroid/di/ViewModelFactoryModule.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/LoveFoodPagingAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/LoveFoodViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/SearchFoodAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/SearchFoodPagingAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/SearchFoodViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SelectHomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/LoveFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/TagFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/MainViewModelProviderFactory.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/SearchViewModelProviderFactory.kt
  app/src/main/res/layout/item_love_restaurant.xml
Labels: refact

#47 refactor(homeFragment): HomeFragment.kt 리팩터링
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/HomeFragment.kt
  app/src/main/res/values/strings.xml
Labels: :hammer:refact, euijin

#48 [feat/ranking] : 관심목록이 비어있을 때 텍스트 변경
  app/src/main/java/com/myongsik/myongsikandroid/data/api/HomeFoodApi.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/db/RestaurantDao.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/food/RequestScrap.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/food/ResponseScrap.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepository.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepositoryImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/HomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SelectFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SplashFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/LoveFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/RestaurantFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/MainViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/SearchViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/GetAdvertisingIdTask.kt
  app/src/main/res/values/strings.xml
Labels: :computer: feat, ssongsik

#50 [feat/ranking] : 홈화면 식당 순위 기능 구현
  app/build.gradle
  app/src/main/java/com/myongsik/myongsikandroid/data/api/HomeFoodApi.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/food/RankRestaurantResponse.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepository.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepositoryImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/SearchFoodPagingSource.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/food/OnScrapViewHolderClick.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/food/RankRestaurantAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/food/RankRestaurantViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/LoveFoodPagingAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/LoveFoodViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/OnSearchViewHolderClick.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/SearchFoodAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/SearchFoodPagingAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/SearchFoodViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/HomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/LoveFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/RestaurantFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/TagFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/MainViewModel.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_restaurant_ranking.xml
  app/src/main/res/values/strings.xml
Labels: :computer: feat, :bell:hotfix, ssongsik

#51 [fix/ranking] : 기존유저를 저장하는 위치를 변경
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/MainActivity.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SplashFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
Labels: :wrench:fix, ssongsik

#55 feat(firebase):Firebase SDK 및 크래시 분석 SDK 추가
  app/build.gradle
  app/google-services.json
  build.gradle
Labels: :computer: feat, euijin

#60 [feat/viewpager_size] : ViewPager 사이즈변경 및 검색화면 수정
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/HomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SplashFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/CommonUtil.kt
  app/src/main/res/drawable-v24/search_food_stroke.xml
  app/src/main/res/drawable/bottom_nav_color_selector.xml
  app/src/main/res/drawable/ic_ep_arrow_left.xml
  app/src/main/res/drawable/search_find_icon.xml
  app/src/main/res/layout/fragment_love.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: :computer: feat, ssongsik

#61 [feat/ranking layout] : 리프레시 레이아웃 추가 및 코드 수정
  app/build.gradle
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
Labels: :computer: feat, euijin

#63 [feat/home scroll] : 전체스크롤 추가
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/food/OnScrapViewHolderClick.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/food/RankHeaderAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/food/RankHeaderViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/header_search_ranking.xml
Labels: :computer: feat, ssongsik

#69 [feat/review] :review Type 추가
  app/src/main/java/com/myongsik/myongsikandroid/data/api/HomeFoodApi.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/review/RequestReviewData.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/SearchFoodAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/HomeFragment.kt
  app/src/main/res/values/strings.xml
Labels: :computer: feat, euijin

#73 [feat/paste] : 주소 및 전화번호 밑줄 추가
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/food/RankRestaurantViewHolder.kt
  app/src/main/res/layout/item_restaurant_ranking.xml
Labels: :computer: feat, euijin
