Repository MYONGSIK/Android, pull requests merged in 2023-05, with the labels that each got.

#106 [fix/remove_love] : 맛있어요, 맛없어요 제거
  app/src/main/java/com/myongsik/myongsikandroid/MainActivity.kt
  app/src/main/java/com/myongsik/myongsikandroid/alarm/AlarmBroadCastReceiver.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepository.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepositoryImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/presentation/adapter/food/MyPagerAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/presentation/view/food/HomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/presentation/viewmodel/food/HomeViewModel.kt
  app/src/main/res/layout/item_home_today_food.xml
Labels: :wrench:fix, ssongsik

#107 [refact/clean] : LoveViewModel 클린아키텍처 마이그레이션
  app/src/main/java/com/myongsik/myongsikandroid/data/api/HomeFoodApi.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/api/RestaurantApi.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/datasource/restaurant/RestaurantDataSource.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/datasource/restaurant/RestaurantDataSourceImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/datasource/user/UserDataSource.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/datasource/user/UserDataSourceImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/db/RestaurantDao.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/food/ResponseScrap.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/kakao/Restaurant.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/restaurant/RequestScrap.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/restaurant/ResponseScrap.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/user/RequestUserData.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/user/ResponseUserData.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepository.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepositoryImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/restaurant/RestaurantRepositoryImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/user/UserRepository.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/user/UserRepositoryImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/di/AppModule.kt
  app/src/main/java/com/myongsik/myongsikandroid/di/RepositoryModule.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/UserCase.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/model/restaurant/RequestScrapEntity.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/model/restaurant/ResponseScrapEntity.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/model/restaurant/RestaurantEntity.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/model/user/RequestUserEntity.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/model/user/ResponseUserEntity.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/repository/restaurant/RestaurantRepository.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/repository/user/UserRepository.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/usecase/restaurant/DeleteRestaurantDataUseCase.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/usecase/restaurant/GetListRestaurantDataUseCase.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/usecase/restaurant/GetPagingRestaurantDataUseCase.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/usecase/restaurant/InsertRestaurantDataUseCase.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/usecase/restaurant/LoveIsRestaurantDataUseCase.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/usecase/restaurant/PostScrapRestaurantDataUseCase.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/usecase/user/PostUserDataUseCase.kt
  app/src/main/java/com/myongsik/myongsikandroid/domain/user/PostUserDataUseCase.kt
  app/src/main/java/com/myongsik/myongsikandroid/presentation/view/food/MapDetailBottomSheetDialog.kt
  app/src/main/java/com/myongsik/myongsikandroid/presentation/view/search/LoveFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/presentation/view/search/RestaurantFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/presentation/viewmodel/food/SplashViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/presentation/viewmodel/search/LoveViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/FoodEvaluation.kt
Labels: :hammer:refact, ssongsik

#109 [feat/admob]: admob 탑재
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/myongsik/myongsikandroid/MainActivity.kt
  app/src/main/java/com/myongsik/myongsikandroid/presentation/view/food/HomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/Constant.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/MyongsikApplication.kt
Labels: :computer: feat, euijin

#110 [feat/home icon] : 홈화면 개편 디자인변경
  app/src/main/java/com/myongsik/myongsikandroid/presentation/adapter/food/RankHeaderViewHolder.kt
  app/src/main/res/drawable/ic_search_bread.xml
  app/src/main/res/drawable/ic_search_cafe.xml
  app/src/main/res/drawable/ic_search_pub.xml
  app/src/main/res/drawable/ic_search_rice.xml
  app/src/main/res/drawable/search_header_icon.xml
  app/src/main/res/layout/header_search_ranking.xml
  app/src/main/res/values/strings.xml
Labels: :computer: feat, dohye
