Repository MYONGSIK/Android, pull requests merged in 2023-04, with the labels that each got.

#85 [fix/dialog backbtn] : 다이얼로그 백버튼 로직 수정
  app/src/main/java/com/myongsik/myongsikandroid/data/model/food/RankRestaurantResponse.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/kakao/SearchResponse.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/food/RankRestaurantViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/DialogUtils.kt
  app/src/main/res/values/strings.xml
Labels: :wrench:fix, ssongsik

#84 [fix/exception]: coroutine exception handler 추가
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SplashFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/BaseViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/MainViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/SearchViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/ErrorConstant.kt
  app/src/main/res/values/strings.xml
Labels: :wrench:fix, euijin

#88 [fix/separation of concerns] : ViewModel 관심사 분리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/myongsik/myongsikandroid/BaseViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/MainActivity.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/food/MyPagerAdapter.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/HomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SelectFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SplashFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/LoveFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/RestaurantFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/TagFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/food/HomeViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/food/SplashViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/search/LoveViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/search/SearchViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: :wrench:fix, ssongsik

#90 [feat/base_fragment] : BaseFragment 모든 Fragment 적용
  app/src/main/java/com/myongsik/myongsikandroid/BaseFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/HomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SelectFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SelectHomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/SplashFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/LoveFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/RestaurantFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/TagFragment.kt
  app/src/main/res/navigation/myongsik_nav_graph.xml
Labels: :computer: feat, ssongsik

#92 [fix/scrap] : Scrap Request, Response 변경
  app/src/main/java/com/myongsik/myongsikandroid/BaseFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/food/RankRestaurantResponse.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/food/RequestScrap.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/kakao/SearchResponse.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/SearchFoodPagingSource.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/RestaurantFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/search/SearchFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/search/SearchViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/Constant.kt
Labels: :wrench:fix, ssongsik

#95 [feat/function_2] : 기능 2 Map 작업
  Android.text
  app/build.gradle
  app/release/output-metadata.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/myongsik/myongsikandroid/BaseFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/MainActivity.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/api/HomeFoodApi.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/food/ResponseOneRestaurant.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepository.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepositoryImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/food/RankRestaurantViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/LoveFoodViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/adapter/search/SearchFoodViewHolder.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/MapDetailBottomSheetDialog.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/MapFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/food/HomeViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/CommonUtil.kt
  app/src/main/jniLibs/arm64-v8a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi-v7a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi/libDaumMapEngineApi.so
  app/src/main/res/drawable/group_14017.xml
  app/src/main/res/drawable/ic_color_call.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_map_marker.xml
  app/src/main/res/drawable/ic_scrap.xml
  app/src/main/res/drawable/ic_selected_marker.xml
  app/src/main/res/drawable/icon_call.xml
  app/src/main/res/drawable/icon_love_shape.xml
  app/src/main/res/drawable/myongsik_bottom_sheet_dialog_background.xml
  app/src/main/res/drawable/place.xml
  app/src/main/res/drawable/rect94_eaeaea.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/custom_balloon.xml
  app/src/main/res/layout/custom_selected_balloon.xml
  app/src/main/res/layout/dialog_bottom_restaurant_sheet.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/header_search_ranking.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/myongsik_nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: :computer: feat, :wrench:fix, ssongsik

#98 [feat/widget type]: 기능 1 타입 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/myongsik/myongsikandroid/alarm/UpdateWidgetWorker.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/api/HomeFoodApi.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/model/food/DayFoodResponse.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepository.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/repository/food/FoodRepositoryImpl.kt
  app/src/main/java/com/myongsik/myongsikandroid/data/type/WidgetType.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/HomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/WidgetSettingFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/food/WidgetSettingViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/widget/MenuWidget.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/CommonUtil.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/DataStoreKey.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/DateUtil.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/MyongsikApplication.kt
  app/src/main/res/drawable/shape_background_round_ffffff.xml
  app/src/main/res/drawable/widget_bottom_round_background_f6f7fa.xml
  app/src/main/res/drawable/widget_round_background_f6f7fa.xml
  app/src/main/res/drawable/widget_top_round_background_f6f7fa.xml
  app/src/main/res/layout/item_widget_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/widget_menu.xml
Labels: :computer: feat, euijin

#100 [feat/update bottom] : 업데이트 바텀시트 다이얼로그 제작 및 버전 업그레이드
  app/build.gradle
  app/release/output-metadata.json
  app/src/main/java/com/myongsik/myongsikandroid/ui/view/food/HomeFragment.kt
  app/src/main/java/com/myongsik/myongsikandroid/ui/viewmodel/food/HomeViewModel.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/CommonUtil.kt
  app/src/main/java/com/myongsik/myongsikandroid/util/PreferenceKey.kt
  app/src/main/res/drawable/ic_color_map.xml
  app/src/main/res/drawable/ic_widget.xml
  app/src/main/res/drawable/rect10_eaeaea.xml
  app/src/main/res/layout/dialog_bottom_update_sheet.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: :computer: feat, ssongsik
